FROM node:18-alpine

WORKDIR /app

COPY package.json package-lock.json* ./

# Install dependencies.
RUN \
  if [ -f package-lock.json ]; then npm ci; \
  else echo "Lockfile not found." && exit 1; \
  fi

# Copy local code to the container image.
COPY . .

EXPOSE 3000

# Set environment variables
ENV NEXT_PUBLIC_API_HOST_URL=http://dev.kino.com/api/v1
ENV NODE_ENV=development
ENV PORT=3000

# Run the web service on container startup.
CMD ["npm", "run", "dev"]
