server.port=${SERVICE_PORT}

spring.application.name=data_service

logging.level.org.springframework.web=${SERVICE_LOGGING_LEVEL}
logging.level.org.springframework.security=${SERVICE_LOGGING_LEVEL}

kino.server.prefix-path=${SERVICE_PREFIX_PATH}
kino.security.form-login.redirect-url=${FORM_LOGIN_REDIRECT_URL}

spring.data.mongodb.host=${MONGO_HOST_ADDRESS}
spring.data.mongodb.port=${MONGO_HOST_PORT}
spring.data.mongodb.database=${MONGO_DATABASE}
spring.data.mongodb.username=${MONGO_USERNAME}
spring.data.mongodb.password=${MONGO_PASSWORD}
# Fixes UncategorizedMongoDbException
spring.data.mongodb.authentication-database=admin

kino.cache.default.redis.host=${REDIS_HOST_ADDRESS}
kino.cache.default.redis.port=${REDIS_PORT}
kino.cache.default.redis.database=${REDIS_DATABASE}
kino.cache.default.redis.username=${REDIS_USERNAME}
kino.cache.default.redis.password=${REDIS_PASSWORD}
kino.cache.default.redis.namespace=${REDIS_NAMESPACE}

kino.cache.session.redis.host=${REDIS_HOST_ADDRESS}
kino.cache.session.redis.port=${REDIS_PORT}
kino.cache.session.redis.username=${REDIS_USERNAME}
kino.cache.session.redis.password=${REDIS_PASSWORD}

spring.kafka.producer.bootstrap-servers=${KAFKA_HOSTS}
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.properties.security.protocol=SASL_PLAINTEXT
spring.kafka.properties.sasl.mechanism=SCRAM-SHA-256
spring.kafka.properties.sasl.jaas.config=org.apache.kafka.common.security.scram.ScramLoginModule required username="${KAFKA_USERNAME}" password="${KAFKA_PASSWORD}";

spring.rabbitmq.host=${RABBITMQ_HOST_ADDRESS}
spring.rabbitmq.port=${RABBITMQ_HOST_PORT}
# spring.rabbitmq.virtual-host=${"RABBITMQ_VHOST"}
spring.rabbitmq.username=${RABBITMQ_USERNAME}
spring.rabbitmq.password=${RABBITMQ_PASSWORD}

spring.security.oauth2.resourceserver.jwt.issuer-uri=${AUTH_SERVER_ISSUER_URI:http://localhost:8081/api/v1/auth}
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${AUTH_SERVER_JWK_SET_URI:http://localhost:8081/api/v1/auth/oauth2/jwks}
spring.security.oauth2.resourceserver.jwt.audiences=${DATA_SERVICE_INTERNAL_AUDIENCE:kino-data-internal}
